version: '3.8'

services:
  frontend:
    container_name: dotnetauth-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8101:80"
    networks:
      - soben-network

networks:
  soben-network:
    external: true